export { default as Home } from './Home';
export { default as Profile } from './Profile';
export { default as Shop } from './Shop';
export { default as Consult } from './Consult';
export { default as AddPet } from './AddPet';
export { default as Chat } from './Chat';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as ForgotPassword } from './ForgotPassword';
